name: CI tests

on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        luaVersion:
          - '5.1'
          - '5.2'
          - '5.3'
          - '5.4'
          - 'luajit'
    steps:
    - uses: actions/checkout@v1
    - uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - uses: leafo/gh-actions-luarocks@v4
    - uses: mymindstorm/setup-emsdk@v11
    - uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.19.2'
    - name: Install luaposix for fuzz test
      run: |
          luarocks install luaposix # for fuzz tests
    - name: Build and test
      run: |
          make ci

  windows:

    runs-on: windows-2019
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Install mingw
      run: |
          choco install mingw
    - name: Build and test executable
      run: |
          cd clib
          make
    - name: Test lua script
      run: |
          ./clib/lua-src/lua test.lua

  macos:

    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        luaVersion:
          - '5.4'
          - 'luajit'
    steps:
    - uses: actions/checkout@v1
    - uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.19.2'
    - uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - uses: leafo/gh-actions-luarocks@v4
    - uses: mymindstorm/setup-emsdk@v11
    - name: Install luaposix for fuzz test
      run: |
          luarocks install luaposix # for fuzz tests
    - name: Build and test
      run: |
          make ci
