name: Djot Implementations
run-name: Djot Implementations
on:
  schedule:
    - cron: "7 * * * 0"

jobs:
  implementations:
    name: Djot Implementations
    runs-on: ubuntu-latest
    steps:
      - name: Install Go Djot
        run: |
          go install github.com/sivukhin/godjot@latest

      - name: Install Haskell Djot
        run: |
          cabal update
          cabal install djot

      - name: Install JavaScript
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install JavaScript Djot
        run: |
          npm install -g @djot/djot

      - name: Install Lua, LuaRocks, and Lua Djot
        run: |
          sudo apt-get --yes install lua5.4 liblua5.4-dev
          wget --quiet https://luarocks.org/releases/luarocks-3.11.1.tar.gz
          tar zxpf luarocks-3.11.1.tar.gz
          cd luarocks-3.11.1
          ./configure && make && sudo make install
          cd ../
          luarocks install --local djot

      - name: Install Rust toolchain and Rust Djot
        run: |
          rustup update stable
          rustup default stable
          cargo install jotdown
          cargo --version
          jotdown --version

      - name: Install Hyperfine
        run: |
          cargo install hyperfine
          hyperfine --version

      - name: Download Pandoc Manual
        run: |
          wget --quiet --no-clobber --output-document=pandoc-manual.dj https://github.com/jgm/djot/files/11900633/pandoc-manual.txt

      - name: Run Benchmarks
        run: >
          hyperfine --warmup 20 --shell=none --export-markdown implementations.md
          "$HOME/go/bin/godjot pandoc-manual.dj"
          "djoths pandoc-manual.dj"
          "djot pandoc-manual.dj"
          "$HOME/.luarocks/bin/djot pandoc-manual.dj"
          "jotdown pandoc-manual.dj"

      - name: Format Markdown File
        run: |
          cat implementations.md
          echo
          echo
          echo "Running on $(lscpu | grep "Model name: [-|(|)| |a-z|A-Z|0-9]*" | sed -e 's/Model name: *//') at $(date --rfc-3339=seconds)  "
          echo "$(go version)  "
          echo "Go djot $(ls $HOME/go/pkg/mod/github.com/sivukhin/)  "
          echo "$(ghc --version)  "
          echo "$(cabal --version) "
          echo "Haskell djot UNKNOWN  "
          echo "npm version $(npm --version)  "
          echo "node version $(node --version)  "
          echo "JavaScript $(djot --version)  "
          echo "$(lua -v)  "
          echo "$(luarocks --version)  "
          echo "Lua $($HOME/.luarocks/bin/djot --version)  "
          echo "$(cargo --version)  "
          echo "$(hyperfine --version)  "
          echo "Rust djot"
          jotdown --version
